services:
  - type: web
    name: heli-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://heli-bot.onrender.com
      - key: RENDER
        value: "true"
