services:
  - type: web
    name: heli-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false   # thiết lập trong dashboard Render
      - key: WEBHOOK_URL
        sync: false   # thiết lập webhook (nếu có)

